name: default

on: [push, workflow_dispatch]

jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      NODE_OPTIONS: '--max-old-space-size=3200'
      CC_TEST_REPORTER_ID: 7997607c5b558cb4d41dc064f3df1a81c07f2de9861ed73c738c23ed8dbab69e
    steps:
      - { uses: actions/checkout@v2, with: { persist-credentials: false } }
      - { uses: actions/setup-node@v2, with: { node-version: 16, cache: 'yarn' } }
      - { name: yarn, run: yarn --frozen-lockfile }

      - name: build
        run: yarn build

      - name: test
        run: |
          curl -s -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          yarn test-ci
          ./cc-test-reporter after-build -t lcov
