name: default

on: [push, workflow_dispatch]

jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      NODE_OPTIONS: '--max-old-space-size=3200'
    steps:
      - { uses: actions/checkout@v2, with: { persist-credentials: false } }
      - { uses: actions/setup-node@v1, with: { node-version: 14 } }
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ github.repository }}-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-deps-v1

      - name: deps
        run: |
          # echo -e "always-auth=true\n//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          yarn --frozen-lockfile

      - name: build
        run: yarn build

      - name: test
        run: yarn test-ci

      - uses: actions/upload-artifact@v2
        with: { name: 'unit.xml', path: 'tmp/jest/unit.xml' }
      - uses: actions/upload-artifact@v2
        with: { name: 'coverage-unit', path: 'coverage/lcov-report' }
