name: release

on:
  push:
    branches: [master, next, act]

jobs:
  release-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env: { NODE_OPTIONS: '--max-old-space-size=3200' }
    steps:
      - { uses: actions/checkout@v3, with: { persist-credentials: true } }
      - { uses: actions/setup-node@v3, with: { node-version: 16, cache: 'yarn' } }

      # Cache for npm/npx in ~/.npm
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-v1-${{ runner.os }}

      - name: yarn
        run: yarn --frozen-lockfile

      - name: build
        run: yarn build-prod

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx @naturalcycles/semantic-release
