name: release

on:
  push:
    branches: [master, next, act]

jobs:
  release-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env: { NODE_OPTIONS: '--max-old-space-size=3200' }
    steps:
      - { uses: actions/checkout@v2, with: { persist-credentials: true } }
      - { uses: actions/setup-node@v2, with: { node-version: 14 } }

      # Cache for npm/npx in ~/.npm
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-v1-${{ runner.os }}

      # Normal cache for yarn in ./node_modules
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: deps-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: yarn
        run: yarn --frozen-lockfile

      - name: build
        run: yarn build-prod

      - name: release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx @naturalcycles/semantic-release
